# -----------------------------------------------------------------------------
# UniquelyIdentifiable
# Generate a UUID for your model
# -----------------------------------------------------------------------------
# This concern requires that you create a uuid column on your model, like so:
#
#   add_column :blog_posts, :uuid, :uuid, null:false, index:true
#
# After including UniquelyIdentifiable, you can then call #uuid on your model
# to retrieve the UUID that will get autogenerated for you:
#
#   @my_model.uuid
#
# Version 4 UUIDs are sufficiently difficult to guess that they can be
# used for secret tokens or other unpredictable but unique identifier needs,
# even across different database tables or synchronization systems.

module UniquelyIdentifiable

  extend ActiveSupport::Concern

  included do

    before_create :initialize_uuid!
    def initialize_uuid!
      begin
        self.uuid = SecureRandom.uuid
      end while self.class.exists?(uuid: self.uuid)
    end

  end

end
